preset: laravel

enabled:
- length_ordered_imports
- long_list_syntax

disabled:
- short_list_syntax
- alpha_ordered_imports
- single_class_element_per_statement

risky: false

preset: laravel

version: 7

tab-width: 4

use-tabs: true

enabled:
  - long_array_syntax
  - length_ordered_imports
  - long_list_syntax

disabled:
  - short_array_syntax
  - alpha_ordered_imports